### ISSUE TITLE
Documentation alludes to multiple scopes but doesn't give examples

### ISSUE THREAD

**Issue by paul-hammant** [dimes/dihedral#3]
I was expecting to see an example of a 'singleton' (application scope) component and how something from less permanent scope may depend on that.

Here's some tangible component names in non HelloWorld application - https://paulhammant.com/blog/a-spring-framework-shortcoming.html

**Comment by dimes** [comment]
Thanks for the example. Both scoping and subcomponents are both under development. I'll update this ticket and docs with a similar example to the one you provided once they are ready.

**Comment by paul-hammant** [comment]
Great!

**Comment by dimes** [comment]
@paul-hammant this is the proposed design of subcomponents. I'd love your feedback on it.

```
// Top-level component interface. Implementation will be generated. 
type ComponentTarget interface {
    InjectedTarget() *Target // Injects some target
}

type Component interface {
    Modules() ComponentBindingModule
    Target() ComponentTarget
}

type ComponentBindingModule interface {
    Modules() OtherModule
    Subcomponents() Subcomponent
}

type Subcomponent interface {
    Target() SubcomponentTarget
}

type SubcomponentTarget interface {
    SubcomponentTarget() *SubcomponentTarget // Some subcomponent type
}
```

Any binding module can specify a list of subcomponents via a `Subcomponents()` interface method. The list of return types specify the interfaces to use as subcomponents. The implementation of this will work by providing the component directly to the subcomponents so that each subcomponent can inject things from the component, but the component won't be able to inject subcomponent things provided by the subcomponent. 

The other part of the proposal is to implement scoping. Scoping serves two purposes:

1. Allow objects to be a singleton in a given scope so that it's not reconstructed each time it's injected. 
2. Enforce the component structure. E.g. a struct scoped to a subcomponent cannot be injected into a parent component. 

Scoping will look like this:

First, a tag struct will be added to the `embeds` package:

```
package embeds

type Scoped struct {}
```

Custom scopes can be added by creating a struct that embeds the scoped struct:

```
type MyCustomScope struct {
    embeds.Scoped
}
```

Components and subscomponents will be required to have a scope:

```
type Component interface {
    Scope() MyCustomScope
    Modules() ComponentBindingModule
    Target() ComponentTarget
}
```

Auto-injected structs declare a scope with a private field:

```
type SomeAutoInjectedType struct {
    inject       embeds.Inject
    scope      MyCustomScope
    // Injected fields...
}
```

What do you think?

**Comment by dimes** [comment]
@paul-hammant I’ve decided to go with a different approach. Rather than explicitly support sub components, I’m going to recommend creating multiple components instead. This way users are free to compose them as they see fit. Closing this out now but would love your feedback.

**Comment by paul-hammant** [comment]
OK, sorry I missed your May comment, I'll take another look at the README.
